/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BASE;

/**
 *
 * @author 23106
 */
public class Frame_RekapMahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form Frame_RekapMahasiswa
     */
    public Frame_RekapMahasiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPILIHMAHASISWA = new javax.swing.JButton();
        btnPEMBAYARANKAS = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableREKAPMAHASISWA = new javax.swing.JTable();
        btnBACK = new javax.swing.JButton();
        LabelRekapMahasiswa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPILIHMAHASISWA.setBackground(new java.awt.Color(46, 144, 232));
        btnPILIHMAHASISWA.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        btnPILIHMAHASISWA.setText("Pilih Mahasiswa");
        getContentPane().add(btnPILIHMAHASISWA, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, 190, 50));

        btnPEMBAYARANKAS.setBackground(new java.awt.Color(233, 174, 200));
        btnPEMBAYARANKAS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPEMBAYARANKAS.setText("Pembayaran Kas");
        getContentPane().add(btnPEMBAYARANKAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 550, 150, 40));

        tableREKAPMAHASISWA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "N I M", "N A M A", "No Handphone", "Jenis Kelamin"
            }
        ));
        jScrollPane1.setViewportView(tableREKAPMAHASISWA);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 730, 270));

        btnBACK.setBackground(new java.awt.Color(51, 255, 204));
        btnBACK.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnBACK.setText("BACK");
        getContentPane().add(btnBACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 559, 110, 40));

        LabelRekapMahasiswa.setBackground(new java.awt.Color(46, 144, 232));
        LabelRekapMahasiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_componen_asset/frame rekap mahasiswa.png"))); // NOI18N
        getContentPane().add(LabelRekapMahasiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_RekapMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_RekapMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_RekapMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_RekapMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_RekapMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelRekapMahasiswa;
    private javax.swing.JButton btnBACK;
    private javax.swing.JButton btnPEMBAYARANKAS;
    private javax.swing.JButton btnPILIHMAHASISWA;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableREKAPMAHASISWA;
    // End of variables declaration//GEN-END:variables
}
