/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BASE;

/**
 *
 * @author 23106
 */
public class Frame_JumlahSaldo extends javax.swing.JFrame {

    /**
     * Creates new form Frame_JumlahSaldo
     */
    public Frame_JumlahSaldo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHITUNG = new javax.swing.JButton();
        btnLOGOUT = new javax.swing.JButton();
        LabelJumlahSaldo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHITUNG.setBackground(new java.awt.Color(141, 80, 199));
        btnHITUNG.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        btnHITUNG.setText("HITUNG");
        btnHITUNG.setBorder(null);
        btnHITUNG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHITUNGActionPerformed(evt);
            }
        });
        getContentPane().add(btnHITUNG, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 510, 110, 50));

        btnLOGOUT.setBackground(new java.awt.Color(0, 0, 204));
        btnLOGOUT.setForeground(new java.awt.Color(255, 255, 255));
        btnLOGOUT.setText("LOG OUT");
        btnLOGOUT.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(btnLOGOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 510, 150, 50));

        LabelJumlahSaldo.setBackground(new java.awt.Color(141, 80, 199));
        LabelJumlahSaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_componen_asset/jumlah saldo.png"))); // NOI18N
        getContentPane().add(LabelJumlahSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHITUNGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHITUNGActionPerformed
        try {
        double inputValue = Double.parseDouble(jTextField1.getText());
        double result = inputValue * 2; 
        JOptionPane.showMessageDialog(null, "Hasil perhitungan: " + result);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Masukkan angka yang valid!");
    }
    }//GEN-LAST:event_btnHITUNGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_JumlahSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_JumlahSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_JumlahSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_JumlahSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_JumlahSaldo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelJumlahSaldo;
    private javax.swing.JButton btnHITUNG;
    private javax.swing.JButton btnLOGOUT;
    // End of variables declaration//GEN-END:variables
}
