/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BASE;

/**
 *
 * @author 23106
 */
public class Frame_PembayaranKas extends javax.swing.JFrame {

    /**
     * Creates new form Frame_PembayaranKas
     */
    public Frame_PembayaranKas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEDIT = new javax.swing.JButton();
        btnKEMBALI = new javax.swing.JButton();
        btnHAPUS = new javax.swing.JButton();
        btnSIMPAN = new javax.swing.JButton();
        txtKETERANGAN = new javax.swing.JTextField();
        radiobuttonPEMASUKAN = new javax.swing.JRadioButton();
        radiobuttonPENGELUARAN = new javax.swing.JRadioButton();
        txtNAMA = new javax.swing.JTextField();
        txtNO = new javax.swing.JTextField();
        txtPEMASUKAN = new javax.swing.JTextField();
        txtPENGELUARAN = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePembayaranKas = new javax.swing.JTable();
        LabelPembayaranKas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEDIT.setBackground(new java.awt.Color(218, 218, 218));
        btnEDIT.setFont(new java.awt.Font("Sylfaen", 1, 22)); // NOI18N
        btnEDIT.setText("EDIT");
        getContentPane().add(btnEDIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 410, 160, 50));

        btnKEMBALI.setBackground(new java.awt.Color(218, 218, 218));
        btnKEMBALI.setFont(new java.awt.Font("Sylfaen", 1, 22)); // NOI18N
        btnKEMBALI.setText("KEMBALI");
        getContentPane().add(btnKEMBALI, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 150, 50));

        btnHAPUS.setBackground(new java.awt.Color(218, 218, 218));
        btnHAPUS.setFont(new java.awt.Font("Sylfaen", 1, 22)); // NOI18N
        btnHAPUS.setText("HAPUS");
        btnHAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHAPUSActionPerformed(evt);
            }
        });
        getContentPane().add(btnHAPUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 160, 50));

        btnSIMPAN.setBackground(new java.awt.Color(218, 218, 218));
        btnSIMPAN.setFont(new java.awt.Font("Sylfaen", 1, 22)); // NOI18N
        btnSIMPAN.setText("SIMPAN");
        getContentPane().add(btnSIMPAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 410, 150, 50));

        txtKETERANGAN.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtKETERANGAN.setText("Uang Masuk");
        getContentPane().add(txtKETERANGAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 260, 40));

        radiobuttonPEMASUKAN.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        radiobuttonPEMASUKAN.setText("PEMASUKAN");
        radiobuttonPEMASUKAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobuttonPEMASUKANActionPerformed(evt);
            }
        });
        getContentPane().add(radiobuttonPEMASUKAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 110, 40));

        radiobuttonPENGELUARAN.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        radiobuttonPENGELUARAN.setText("PENGELUARAN");
        radiobuttonPENGELUARAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobuttonPENGELUARANActionPerformed(evt);
            }
        });
        getContentPane().add(radiobuttonPENGELUARAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, -1, -1));

        txtNAMA.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtNAMA.setText("Najwa Latifah");
        txtNAMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNAMAActionPerformed(evt);
            }
        });
        getContentPane().add(txtNAMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 240, 260, 40));

        txtNO.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtNO.setText("1");
        getContentPane().add(txtNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 240, 40));

        txtPEMASUKAN.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtPEMASUKAN.setText("200.000");
        txtPEMASUKAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPEMASUKANActionPerformed(evt);
            }
        });
        getContentPane().add(txtPEMASUKAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 110, 240, 40));

        txtPENGELUARAN.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtPENGELUARAN.setText("100.000");
        getContentPane().add(txtPENGELUARAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, 240, 40));

        tablePembayaranKas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "N O", "Tanggal", "Nama", "Pemasukan", "Pengeluaran", "Keterangan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablePembayaranKas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 980, 200));

        LabelPembayaranKas.setFont(new java.awt.Font("Sylfaen", 1, 22)); // NOI18N
        LabelPembayaranKas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_componen_asset/pembayaran kas.png"))); // NOI18N
        getContentPane().add(LabelPembayaranKas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHAPUSActionPerformed
        int selectedRow = table.getSelectedRow();
    if (selectedRow != -1) {
        model.removeRow(selectedRow); // Menghapus baris dari tabel model
        JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
    } else {
        JOptionPane.showMessageDialog(null, "Pilih data yang akan dihapus!");
    }
    }//GEN-LAST:event_btnHAPUSActionPerformed

    private void radiobuttonPEMASUKANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobuttonPEMASUKANActionPerformed
        category = "Pemasukan"; 
    JOptionPane.showMessageDialog(null, "Kategori: Pemasukan dipilih.");
    }//GEN-LAST:event_radiobuttonPEMASUKANActionPerformed

    private void radiobuttonPENGELUARANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobuttonPENGELUARANActionPerformed
        category = "Pengeluaran"; 
    JOptionPane.showMessageDialog(null, "Kategori: Pengeluaran dipilih.");
    }//GEN-LAST:event_radiobuttonPENGELUARANActionPerformed

    private void txtNAMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNAMAActionPerformed
       String name = txtNAMA.getText();
    if (!name.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Nama diinput: " + name);
    } else {
        JOptionPane.showMessageDialog(null, "Nama tidak boleh kosong!");
    }
    }//GEN-LAST:event_txtNAMAActionPerformed

    private void txtPEMASUKANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPEMASUKANActionPerformed
        try {
        double amount = Double.parseDouble(txtPEMASUKAN.getText());
        JOptionPane.showMessageDialog(null, "Pemasukan sebesar: " + amount);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Masukkan angka yang valid untuk pemasukan!");
    }
    }//GEN-LAST:event_txtPEMASUKANActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_PembayaranKas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_PembayaranKas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_PembayaranKas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_PembayaranKas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_PembayaranKas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelPembayaranKas;
    private javax.swing.JButton btnEDIT;
    private javax.swing.JButton btnHAPUS;
    private javax.swing.JButton btnKEMBALI;
    private javax.swing.JButton btnSIMPAN;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radiobuttonPEMASUKAN;
    private javax.swing.JRadioButton radiobuttonPENGELUARAN;
    private javax.swing.JTable tablePembayaranKas;
    private javax.swing.JTextField txtKETERANGAN;
    private javax.swing.JTextField txtNAMA;
    private javax.swing.JTextField txtNO;
    private javax.swing.JTextField txtPEMASUKAN;
    private javax.swing.JTextField txtPENGELUARAN;
    // End of variables declaration//GEN-END:variables
}
