/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BASE;

/**
 *
 * @author 23106
 */
public class Frame_DataMahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form Frame_DataMahasiswa
     */
    public Frame_DataMahasiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNIM = new javax.swing.JTextField();
        txtNOHP = new javax.swing.JTextField();
        txtNAMA = new javax.swing.JTextField();
        ComboboxJenisKelamin = new javax.swing.JComboBox<>();
        btnSIMPAN = new javax.swing.JButton();
        btnKEMBALI = new javax.swing.JButton();
        labelDataMahasiswa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNIM.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtNIM.setBorder(null);
        getContentPane().add(txtNIM, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 170, 250, 50));

        txtNOHP.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtNOHP.setBorder(null);
        getContentPane().add(txtNOHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 250, 50));

        txtNAMA.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        txtNAMA.setBorder(null);
        txtNAMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNAMAActionPerformed(evt);
            }
        });
        getContentPane().add(txtNAMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, 250, 50));

        ComboboxJenisKelamin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ComboboxJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki Laki", "Perempuan", "" }));
        getContentPane().add(ComboboxJenisKelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 270, 190, 50));

        btnSIMPAN.setBackground(new java.awt.Color(204, 204, 204));
        btnSIMPAN.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        btnSIMPAN.setText("SIMPAN");
        getContentPane().add(btnSIMPAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, 140, 60));

        btnKEMBALI.setBackground(new java.awt.Color(204, 204, 255));
        btnKEMBALI.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        btnKEMBALI.setText("KEMBALI");
        btnKEMBALI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKEMBALIActionPerformed(evt);
            }
        });
        getContentPane().add(btnKEMBALI, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 550, 140, 60));

        labelDataMahasiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_componen_asset/frame Data Mahasiswa.png"))); // NOI18N
        getContentPane().add(labelDataMahasiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNAMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNAMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNAMAActionPerformed

    private void btnKEMBALIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKEMBALIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKEMBALIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_DataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_DataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_DataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_DataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_DataMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboboxJenisKelamin;
    private javax.swing.JButton btnKEMBALI;
    private javax.swing.JButton btnSIMPAN;
    private javax.swing.JLabel labelDataMahasiswa;
    private javax.swing.JTextField txtNAMA;
    private javax.swing.JTextField txtNIM;
    private javax.swing.JTextField txtNOHP;
    // End of variables declaration//GEN-END:variables
}
