/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BASE;

/**
 *
 * @author 23106
 */
public class Frame_MenuUtamaFix extends javax.swing.JFrame {

    /**
     * Creates new form Frame_MenuUtama
     */
    public Frame_MenuUtamaFix() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDataMahasiswa = new javax.swing.JButton();
        btnPembayaanKas = new javax.swing.JButton();
        btnJumlahSaldo = new javax.swing.JButton();
        btnLOGOUT = new javax.swing.JButton();
        labelMenuUtama = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDataMahasiswa.setBackground(new java.awt.Color(51, 255, 255));
        btnDataMahasiswa.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnDataMahasiswa.setText("Data Mahasiswa");
        getContentPane().add(btnDataMahasiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 210, 40));

        btnPembayaanKas.setBackground(new java.awt.Color(255, 255, 102));
        btnPembayaanKas.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnPembayaanKas.setText("Pembayaran Kas");
        btnPembayaanKas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPembayaanKasActionPerformed(evt);
            }
        });
        getContentPane().add(btnPembayaanKas, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, 210, 40));

        btnJumlahSaldo.setBackground(new java.awt.Color(204, 0, 204));
        btnJumlahSaldo.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        btnJumlahSaldo.setText("Jumlah Saldo");
        getContentPane().add(btnJumlahSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 420, 170, 40));

        btnLOGOUT.setBackground(new java.awt.Color(255, 0, 0));
        btnLOGOUT.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        btnLOGOUT.setForeground(new java.awt.Color(255, 255, 255));
        btnLOGOUT.setText("LOG OUT");
        getContentPane().add(btnLOGOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 540, 160, 40));

        labelMenuUtama.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        labelMenuUtama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_componen_asset/3.png"))); // NOI18N
        getContentPane().add(labelMenuUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPembayaanKasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembayaanKasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPembayaanKasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_MenuUtamaFix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_MenuUtamaFix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_MenuUtamaFix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_MenuUtamaFix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_MenuUtamaFix().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDataMahasiswa;
    private javax.swing.JButton btnJumlahSaldo;
    private javax.swing.JButton btnLOGOUT;
    private javax.swing.JButton btnPembayaanKas;
    private javax.swing.JLabel labelMenuUtama;
    // End of variables declaration//GEN-END:variables
}
